# Generated by Django 4.2.2 on 2023-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='data1', max_length=10, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
