# Generated by Django 4.2.2 on 2023-06-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filemodel_mode_filemodel_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='schema',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='mode',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ANY', 'ANY'), ('NONE', 'NONE')], default='Choose Mode', max_length=40),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='title',
            field=models.CharField(blank=True, default='brokenData', max_length=10, null=True),
        ),
    ]
